import React from 'react';
import Head from 'next/head';
import Link from 'next/Link';

const Layout = ({ children, title }) => {
    return (
        <>
            <Head>
                <title>{title ? title + ' - Amazona' : 'Amazona'}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex min-h-screen flex-col justify-between">
                <header>
                    <nav className="flex h-12 px-4 items-center justify-between shadow-md">
                        <Link href="/">
                            <a className="font-lg font-bold">amazona</a>
                        </Link>
                        <div className="">
                            <Link href="/cart">
                                <a className="p-2">Cart</a>
                            </Link>
                            <Link href="/login">
                                <a className="p-2">Login</a>
                            </Link>
                        </div>
                    </nav>
                </header>
                <main className="container m-auto mt-4 px-4">{children}</main>
                <footer className="flex h-10 justify-center items-center shadow-inner">
                    <p>Copyright &copy; {new Date().getFullYear()} Amazona</p>
                </footer>
            </div>
        </>
    );
};

export default Layout;
